rules:
  - p/default
  - p/cwe-top-25
  - p/trailofbits
  - p/owasp-top-ten

paths:
  # Ignore this specific file which causes false positives
  ignore:
    - library/uv.lock
    - application/backend/uv.lock