# TURN server configuration

# Listener port for TURN relay
listening-port=443

# Replace with the host's IP address.
# external-ip=10.123.246.154

# Credentials
# For production, consider using use-auth-secret
user=user:password
realm=my-realm

# Force TCP relay (since UDP is blocked)
no-udp
no-tcp-relay=0

# Log to stdout
log-file=stdout
verbose
